# Generated by Django 5.2.16 on 2026-10-01 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_digest', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('count__lte', 10)), name='users_login_limit')],
            },
        ),
        migrations.CreateModel(
            name='IdentityReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=80)),
                ('operation', models.CharField(max_length=32)),
                ('key_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('response', models.JSONField(null=True)),
                ('status', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'operation', 'key_digest'), name='users_unique_identity_receipt'), models.CheckConstraint(condition=models.Q(models.Q(('response__isnull', True), ('status__isnull', True)), models.Q(('response__isnull', False), ('status__isnull', False), ('user__isnull', False)), _connector='OR'), name='users_consistent_receipt')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_mode', models.CharField(blank=True, choices=[('START_ZERO', 'Start Zero'), ('DIAGNOSTIC', 'Diagnostic'), ('SELF_REPORT', 'Self Report')], max_length=16, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('onboarding_complete', False), ('onboarding_mode__isnull', True)), models.Q(('onboarding_complete', True), ('onboarding_mode__in', ['START_ZERO', 'DIAGNOSTIC', 'SELF_REPORT']), ('onboarding_mode__isnull', False), ('selected_grade__isnull', False)), _connector='OR'), name='users_consistent_onboarding')],
            },
        ),
    ]
